{{ $platform_name := "spaced-rep-tool-web"}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nova-front.fullname" . }}-{{ $platform_name }}
  labels:
    {{- include "nova-front.deploymentLabels" . | nindent 4 }}
    app: {{ include "nova-front.fullname" . }}-{{ $platform_name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "nova-front.fullname" . }}-{{ $platform_name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nova-front.deploymentLabels" . | nindent 8 }}
        app: {{ include "nova-front.fullname" . }}-{{ $platform_name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nova-front.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: {{ .Chart.Name }}-npm-ci
        image: busybox:latest
        workingDir: /usr/src/server/                  ############################## REWORK!!!!!
        # workingDir: {{ .Values.workingDir }}      ############################## REWORK!!!!!
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              wget http://nginx-static-files.nova-dev.svc.cluster.local/{{.Release.Namespace}}/spaced-rep-tool-web.zip &&
              unzip -o spaced-rep-tool-web.zip &&
              rm spaced-rep-tool-web.zip
        volumeMounts:                       ############################## REWORK!!!!!
        - name: nova-{{ $platform_name }}              ############################## REWORK!!!!!
          mountPath: "/usr/src/server/"     ############################## REWORK!!!!!
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: node:22            ############################## REWORK!!!!!
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /usr/src/server/apps/spaced-rep-tool-web/             ############################## REWORK!!!!!
          command: ["npm"]
          args: ["run", "dev", "--", "--host"]
          env:          
            - name: "GATEWAY_HOST"
              value: "nova-api-gateway-service.{{.Release.Namespace}}.svc.cluster.local"
            - name: "VITE_API_V1_URL"
              value: "https://{{ .Values.application_environment }}.memo.{{ .Values.domain_name }}/api/v1/" ### make variables for it
          # command: ["npm"]
          # args: ["run", "vite", "preview"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            null
          readinessProbe:
            null
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:                       ############################## REWORK!!!!!
          - name: nova-{{ $platform_name }}               ############################## REWORK!!!!!
            mountPath: "/usr/src/server/"     ############################## REWORK!!!!!

      volumes:                              ############################## REWORK!!!!!
      - name: nova-{{ $platform_name }}         ############################## REWORK!!!!!
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nova-front.fullname" . }}-{{ $platform_name }}-service
  labels:
    app: {{ include "nova-front.fullname" . }}-{{ $platform_name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ include "nova-front.fullname" . }}-{{ $platform_name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nova-front.fullname" . }}-{{ $platform_name }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.application_environment }}.memo.{{ .Values.domain_name }}
      secretName: qa1-memo-novaenglish-by-tls
  rules:
  - host: {{ .Values.application_environment }}.memo.{{ .Values.domain_name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "nova-front.fullname" . }}-{{ $platform_name }}-service
            port:
              number: 80