import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import SideMenuLayout from "@/app/layouts/SideMenuLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope({
  subsets: ["latin", "cyrillic"],
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <SideMenuLayout>{children}</SideMenuLayout>
      </body>
    </html>
  );
}
