import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import SideMenuLayout from '@/app/layouts/SideMenuLayout';
import { Header } from '@/components/Header/Header';
import { ReactNode } from 'react';
import { SsrStageBanner } from '@sharedutils/ssrStageBanner.component';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const manrope = Manrope({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-manrope',
  weight: ['200', '300', '400', '500', '600', '700', '800'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        {process.env.NEXT_PUBLIC_VITE_APP_ENV !== 'prod' && <SsrStageBanner />}
        <Header />
        <SideMenuLayout>{children}</SideMenuLayout>
      </body>
    </html>
  );
}
