import Footer from "@/components/footer/ui/footer.components"
import Header from "@/components/header/ui/header.component"
import LangSwitcher from "@/features/LandSwitcher/ui/LangSwitcher.component"
import type { Metadata } from "next"
import { NextIntlClientProvider } from "next-intl"
import { getMessages } from "next-intl/server"
import { Manrope } from "next/font/google"
import "../global.css"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}
const manrope = Manrope({
	subsets: ["latin", "cyrillic"],
	variable: "--font-manrope",
	weight: ["200", "300", "400", "500", "600", "700", "800"]
})

export default async function RootLayout({
	children,
	params: { locale }
}: {
	children: React.ReactNode
	params: { locale: string }
}) {
	const messages = await getMessages()

	return (
		<html lang={locale}>
			<body className={manrope.className}>
				<NextIntlClientProvider messages={messages}>
					<Header />
					<LangSwitcher />
					<main>{children}</main>
					<Footer />
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
