name: Test and Build on Pull Request

# on:
#   pull_request:
#   push:
#     branches:
#       - main
on: workflow_dispatch

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npx turbo lint

      - name: Run tests
        run: npx turbo test --continue

      - name: Build the projects without caching
        run: npx turbo build --continue --force
