name: Build project

on: workflow_dispatch

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx turbo test --continue

      - name: Build the project
        run: npx turbo build --continue
      
      - name: Archive production artifacts admin-portal
        uses: actions/upload-artifact@v4
        with:
          name: admin-portal
          path: |
            apps/admin-portal/dist
      - name: Archive production artifacts spaced-rep-tool-mobile
        uses: actions/upload-artifact@v4
        with:
          name: spaced-rep-tool-mobile
          path: |
            apps/spaced-rep-tool-mobile/dist
      - name: Archive production artifacts spaced-rep-tool-web
        uses: actions/upload-artifact@v4
        with:
          name: spaced-rep-tool-web
          path: |
            apps/spaced-rep-tool-web/dist
      - name: Copy needed modules nova-english-marketing-website
        run: |
          cp -r node_modules/@next/ apps/nova-english-marketing-website/node_modules/
          cp -r node_modules/@swc/ apps/nova-english-marketing-website/node_modules/
          cp -r node_modules/next/ apps/nova-english-marketing-website/node_modules/
          cp -r node_modules/react/ apps/nova-english-marketing-website/node_modules/
          cp -r node_modules/react-dom/ apps/nova-english-marketing-website/node_modules/
          cp -r node_modules/styled-jsx/ apps/nova-english-marketing-website/node_modules/
      - name: Archive production artifacts nova-english-marketing-website
        uses: actions/upload-artifact@v4
        with:
          name: nova-english-marketing-website
          path: |
            apps/nova-english-marketing-website/.next
            apps/nova-english-marketing-website/next.config.*js
            apps/nova-english-marketing-website/node_modules
            apps/nova-english-marketing-website/package.json
      - name: Copy needed modules student-platform
        run: |
          cp -r node_modules/@next/ apps/student-platform/node_modules/
          cp -r node_modules/@swc/ apps/student-platform/node_modules/
          cp -r node_modules/next/ apps/student-platform/node_modules/
          cp -r node_modules/react/ apps/student-platform/node_modules/
          cp -r node_modules/react-dom/ apps/student-platform/node_modules/
          cp -r node_modules/styled-jsx/ apps/student-platform/node_modules/
      - name: Archive production artifacts student-platform
        uses: actions/upload-artifact@v4
        with:
          name: student-platform
          path: |
            apps/student-platform/.next
            apps/student-platform/next.config.*js
            apps/student-platform/node_modules
            apps/student-platform/package.json
            
